### PR TITLE
Add LaTeX table generator

### PR DESCRIPTION
**Pull request by awf**
Add LaTeX table generator
Fix link to Colab
Improve tables in notebook

### CODE REVIEW

**Comment by awf** [comment]
@JeffreySarnoff For your consideration

**Comment by P3109** [comment]
suggestions:
in this table
  name precision emax mantBits expBits expBias all_bits_one_full has_nz
has_infs
(1) rename has_nz ("±0") or "has_negzero" or footnote it to clarify
(2) all_bits_one_full does not mean anything to me, what is it?
(3) footnote precision "all significant bits (includes the implicit bit)"
(4) footnote mantBits "explicit significand bits"
maybe footnote all cols or just give each a very short explanation before
or after the table.

in the tables
ival ...
you have the same value repeated in the first and second cols, better to
make the second column name "encoding" or "code" and give the 0xnn form of
the integer as the values in that column.
The column "fval" appears to be binary16 values and the column "valstr"
appears to be binary32 values.  It is clearer and more helpful to be
explicit, labelling each as such.  Also valstr is misleading as the string
form of a binary16 value does not have the extra digits. "signstr" should
pbly be "sign" .

IMPORTANT: zero is not subnormal and zero is not normal. Zero,  ±Inf, NaN
are neither normal nor subnormal values -- I have been calling them
"special values" and calling values that are either normal or subnormal
"ordinary values" although "typical" or "common" values might be better.
In any event I am not suggesting a column that uses that combined
characterization. Rather than the "issubnormal" column, you could label it
"class"  with entries "subnormal" "normal" "zero" "infinity" or, to be
pedantic, "+subnormal" "+normal" "zero" "+infinity" and "-subnormal",
"-normal", "-infinity". Since you have a column for the sign, repeating the
sign here is unnecessary -- otoh it may be more tidy to  use the pedantic
forms and remove your sign column (keeping the sign bit column). I prefer
the tidy version.

754-2019 pp14-15, 38:  Internal copy of 754
<https://ieee-sa.imeetcentral.com/p3109wgpublic/folder/WzIwLDEzNjM3MTAxXQ/WzIsODQ4MTA2MjBd/>
*normal number*: For a particular format, a finite non-zero floating-point
number with magnitude greater than or equal to a minimum b^emin value,
where b is the radix. Normal numbers can use the full precision available
in a format. In this standard, zero is neither normal nor subnormal.
*subnormal number*: In a particular format, a non-zero floating-point
number with magnitude less than the magnitude of that format’s smallest
normal number. A subnormal number does not use the full precision available
to normal numbers of the same format.
*class(x)* tells which of the following ten classes x falls into:
signalingNaN
quietNaN
negativeInfinity
negativeNormal
negativeSubnormal
negativeZero
positiveZero
positiveSubnormal
positiveNormal
positiveInfinity.

The column "exp" should either be "biased exp" or footnoted or explained
before or after the table.

There is no defined term "mantissa" any more. The explicit bits of the
significand are called the "trailing significand field" (which is the
reason it is assigned "t" like precision is assigned "p"). See 754-2019 pg
19. Internal copy of 754
<https://ieee-sa.imeetcentral.com/p3109wgpublic/folder/WzIwLDEzNjM3MTAxXQ/WzIsODQ4MTA2MjBd/>
You
could label the column ?? and explain it before or after the table.

756 p16:
*significand*: A component of a finite floating-point number containing its
significant digits. The significand can be thought of as an integer, a
fraction, or some other fixed-point form, by choosing an appropriate
exponent offset. A decimal or subnormal binary significand can also contain
leading zeros, which are not
significant.

The columns labeled "xxxval" read more clearly as "xxx val".

I am looking at the remaining tables now
Best,
Jeffrey

**Comment by P3109** [comment]
In the table "name P E M ..."

If there is not yet an explanation/decoding of P E M lt1 ge1 rt16 rt32,
there should be.

If all values in all formats round trip with binary32, there is no need
for that column.  A clear statement of that fact should suffice.
If some formats do not round trip with binary32 and do round trip with
binary64 then a column "roundtrip" or "intercvt" (either also explained)
that has entries of binary16, binary32, binary64 makes sense (replacing
rt16, rt32).  With a single column, even if it be that all formats round
trip with binary32, you could have the two entries binary16, binary32
present.

NaN is not a subnormal -- so minsubnormal cannot be NaN use either the
empty set ∅  or else N/A (not applicable) and add that to the
explanations). The same with minnormal and maxnormal.

In this table the ocp_s are at the end of the table. You should do this
with the other tables. It makes them easier to read.
A small vertical whitespace separator or a thin grey horizontal line before
the ocp_s might work well -- I would have to see that to know.

Why are there row numbers at the left? Do they serve a purpose here? If
they do, why are they zero indexed?

In the entries like "1*2^31.0, 1*2^-31.0"  all of the powers are of the
form <integer>.0, so drop the ".0"s in this / these table[s].
(I know that form came from something I did -- however, I later discovered
it was not needed).

I am looking at the value tables now.

Best,
Jeffrey



namePEMlt1ge1rt16rt32maxFiniteminFinitemaxNormalminNormalminSubnorm

**Comment by P3109** [comment]
Regarding the value tables:

There are many entries "~<value>". Assuming that column is intended to have
binary32 values (it appears so), there is a better way.
This is Julia, I intend it to be self explanatory (let me know if there are
questions).
```
function ldexp32(x::Float64)
    binaryfraction, binaryexponent = frexp(x)
    binary32fraction = Float32(binaryfraction)
    binary32result =  ldexp(binary32fraction, binaryexponent)
    return binary32result
end
```
I don't know how to make python print out a binary32 value without it
appearing as a "python double".
Julia does it; Float32(x) converts x to binary32 and prints it as such.
The point of all this is that

(a) for example binary8p3 0x09 = (1 + 1/4) * 2^-14 = 7.62939453125e-5
(binary64) [in table it is  ~7.6293945e-05]
ldexp32(7.62939453125e-5) == 7.6293945f-5 (the f denotes binary32, just as
e-5 denotes binary64),
and --> Float64(7.6293945f-5) == 7.62939453125e-5; so a binary32 table
entry of 7.6293945f-5 is exact, no ~needed.

(b) binary8p3 0x13 = (1+ 3/4) * 2^-12 = 0.00042724609375 (binary64) [in
table it is ~0.00042724609]
x = 0.00042724609375; y = ldexp32(x); y == 0.0004272461f0 == 0.0004272461
(Float32).
Float64(y) == 0.00042724609375 == x and the ~ is not needed with a table
entry of 0.0004272461.
note that Float64(0.00042724609) == 0.00042724609, which is inexact as
shown by the ~.

AS FAR AS I KNOW, all of our table entries have exact Float32 values

>> if it would be helpful for me to generate the Float32 values as they
should be printed, let me know
>> Given e.g. one csv file with the Float64s (python doubles) in encoding
order for each format, I could do that quickly.

For these tables to read correctly, either give the columns headings or use
e.g "0x01 = 0_00000_01 = .."

0x01 0_00000_01 = +0b0.01*2^-15 = ~7.6293945e-06


Since we want these tables in the doc, consider splitting them in half?

Best,
Jeffrey

**Comment by awf** [comment]
Thanks for the extensive (to say the least :)) comments.  Most have been enacted in the latest push - others might take more time, so I propose we omit them in this PR.

**Pull request merged**
